<?php
echo "<h1>Exercícios de Algoritmo </h1>";

echo "<ol>";
echo "<li><a href=\"./exercicio1.php\">Exercício 1 - Como trocar um pneu furado ?</a></li>";
echo "<li><a href=\"./exercicio2.php\">Exercício 2 - Calcule o IMC</a></li>";
echo "<li><a href=\"./exercicio3.php\">Exercício 3 - Idade</a></li>";
echo "<li><a href=\"./exercicio4.php\">Exercício 4 - Saldo Bancário</a></li>";
echo "<li><a href=\"./exercicio5.php\">Exercício 5 - IMC condicional</a></li>";
echo "<li><a href=\"./exercicio6.php\">Exercício 6 - Classificação de Menor Idade</a></li>";
echo "<li><a href=\"./exercicio7.php\">Exercício 7 - Saldo II</a></li>";
echo "<li><a href=\"./exercicio8.php\">Exercício 8 - Operações Aritméticas</a></li>";
echo "<li><a href=\"./exercicio9.php\">Exercício 9 - Base de Figuras Geométricas</a></li>";
echo "<li><a href=\"./exercicio10.php\">Exercício 10 - Múltiplos de 100</a></li>";
echo "<li><a href=\"./exercicio11.php\">Exercício 11 - Tabuada</a></li>";
echo "<li><a href=\"./exercicio12.php\">Exercício 12 - Múltiplos de 3</a></li>";
echo "<li><a href=\"./exercicio13.php\">Exercício 13 - Operações Bancárias</a></li>";
echo "<li><a href=\"./exercicio14.php\">Exercício 14 - Tabuada II</a></li>";
echo "<li><a href=\"./exercicio15.php\">Exercício 15 - Login e Senha</a></li>";
echo "<li><a href=\"./exercicio16.php\">Exercício 16 - Operações Matemáticas</a></li>";
echo "<li><a href=\"./exercicio17.php\">Exercício 17 - </a></li>";
echo "<li><a href=\"./exercicio18.php\">Exercício 18 - </a></li>";
echo "<li><a href=\"./exercicio19.php\">Exercício 19 - </a></li>";
echo "<li><a href=\"./exercicio20.php\">Exercício 20 - </a></li>";
echo "<li><a href=\"./exercicio21.php\">Exercício 21 - </a></li>";
echo "<li><a href=\"./exercicio22.php\">Exercício 22 - </a></li>";
echo "<li><a href=\"./exercicio23.php\">Exercício 23 - </a></li>";
echo "<li><a href=\"./exercicio24.php\">Exercício 24 - </a></li>";
echo "<li><a href=\"./exercicio25.php\">Exercício 25 - </a></li>";
echo "</ol>";
